<a href="https://colab.research.google.com/github/ms-daniel/Exercicio-IA-Rede-Neural/blob/main/IA_Ex09_Diabetes_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [2]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/ms-daniel/Exercicio-IA-Rede-Neural/main/base_de_dados_diabetes.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento[:,:])
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:,:8])
print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])


---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
----------------------------
Classificação Supervisionada
----------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1

### Pré-processamento de Dados

In [3]:
import numpy as np
from sklearn import preprocessing

# Normalizar atributos de entrada entre [0,1]
# min_max será o transformador que irá normalizar os atributos de entrada
# e também os atributos a serem utilizados como testes (células seguintes...)
min_max = preprocessing.MinMaxScaler()
atributos_norm = min_max.fit_transform(base_Treinamento[:,:8])

# Testar sem normalização dos dados
#atributos_norm = base_Treinamento[:,:8]
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)
diagnostico_norm = base_Treinamento[:, 8]
print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.

### Treinamento do KNN (K-Nearest Neighbor)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
# Treinamento do Knn a partir dos atributos de entrada e classificações com K=3
modelo = KNeighborsClassifier()
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo. 
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 0.794


### ----------------------------------------------------------------------------

# Validação do Aprendizado 

### Predição Simples

In [9]:
Luiz = [[6,148,72,35,0,33.6,0.627,50]]
Luiz_minmax = min_max.transform(Luiz)
print("Luiz", modelo.predict(Luiz_minmax))

Laura = [[1,85,66,29,0,26.6,0.351,31]]
Laura_minmax = min_max.transform(Laura)
print("Laura", modelo.predict(Laura_minmax))

Luiz [1.]
Laura [0.]


### Predição a partir de base de dados (.csv)

In [ ]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/ms-daniel/Exercicio-IA-Rede-Neural/main/base_de_dados_diabetes_testes.csv'
base_Testes = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:,0:8])

### Pré-processamento de Dados

In [ ]:
import numpy as np
from sklearn import preprocessing

# Normalizar atributos de entrada entre [0,1]
# min_max será o transformador que irá normalizar
# os atributos a serem utilizados como testes
atributos_norm = min_max.transform(base_Testes[:,:8])

# Testar sem normalização dos dados
#atributos_norm = base_Testes[:,:8]
#Atributos (Colunas)
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)


### Predição da Base

In [12]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.
 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1.]
